### ISSUE TITLE
[FEATURE] Get Pokecord Prefix from message

### ISSUE THREAD

**Issue by triple7inc** [0xSteeW/JokerCord#33]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when they call me out for a bot.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Going to describe it here.

Create a function in your bot_thread.py such as:
`async def GetPrefix(e):
	if e==None:return"p!"
	return e.description.split("type ")[1].split("catch")[0]`
Then you can call it simply with `prefix=GetPrefix(embed)`
thus very easily replace
`await message.channel.send("p!catch "+save_line.lower())`
with
`await message.channel.send(prefix+"catch "+save_line.lower())`

I'd bet you're smart enuf to understand this above.

**Comment by joker-ware** [comment]
Thanks for your suggestion! I will see when I will be able to introduce it into the code. Unfortunately I haven't been working as much in this project because it as kind of a begginer one for Python, but I am looking forward to port it to another language like C++ as I feel more comfortable there. If you have more suggestions like this please post them!

**Comment by triple7inc** [comment]
Sure! I actually wrote an almost undetectable (well.. they took 3 days on this version) for DankMemer also so if you are interested in the code. Holla. Also in python. I'll have more ideas soon when I discover more of the game.

**Comment by triple7inc** [comment]
You should also add human breaks. Just take every x to x catches and let it pause for 15-30 minutes or even more.. this way people could easily run it all day while being away.. if anybody checks they will see the gaps and think that it's just another lonely gamer. More random intervals = more human-like

**Comment by triple7inc** [comment]
What about this for the spam:
`await channel.send("["+str(random.randint(1000000000,2147483647))+"] "+prefs["auto_spam_text"],delete_after=random.randint(90,180))`

This way we clean-up after ourselves and while adding a random integer infront of the message there is a more frequent chance of pokemons actually spawning.
Any bot detection towards simply checking if message is exactly as one of in it's history, probably last 10, it will count as a single one.. and maybe even with the custom message, rule it out and add a random string so no advanced bot detection could be used on that.. only when looking at it of course.. then it is obvious haha.

**Comment by triple7inc** [comment]
... or how about scrambling the whole word and coming up with something else. You can add checks for that this is just a simple example:
`try:
        if(prefs["auto_spam"]=="True"):
            word=list(prefs["auto_spam_text"])
            while(1):
                #try:
                random.shuffle(word)
                auto_spam_text=''.join(word)
                if(prefs["auto_spam_interval"]=="R"):
                    channel=client.get_channel(int(prefs["auto_spam_channel"]))
                    await channel.send("["+str(random.randint(1000000000,2147483647))+"] "+auto_spam_text+" "+str(hash(random.getrandbits(64))),delete_after=random.randint(90,180))
                    rand=random.randrange(1,20)
                    await asyncio.sleep(rand)
                else:
                    channel=client.get_channel(int(prefs["auto_spam_channel"]))
                    await channel.send("["+str(random.randint(1000000000,2147483647))+"] "+auto_spam_text+" "+str(hash(random.getrandbits(64))),delete_after=random.randint(90,180))
                    await asyncio.sleep(int(prefs["auto_spam_interval"]))
    except:
        print("Something went wrong with the channel id.")`

**Comment by triple7inc** [comment]
Example output:

**
[2080429352] NAPOH Z ZMIKA 535244826481265735
[1156445433] I ZPKOAANZMH  1367655527257889705
[1720730748] ONPA ZAZHKMI  2059630771395940101
[1981155366] ZAPHKMOA ZNI  1445045564399098774
[2081959070] NZMKAI OZHA P 71099472387658137
[1642533811] AZNOMA ZKIPH  1253112764571161614
[1643867810] IA NMAPZZ KHO 270092601047330383
[1054972790] P ZKOHM ZAAIN 1445065015281464359
[1507998913] AOZP ZINMKAH  755059768459941329
[1637434283] ZAK ONPAM IZH 330147796111730165
[1703597159] HK OAMIZ ANPZ 720747799299248882
[1454717285] PKZHOI NZMA A 2117581741342080975
[1650362382] A ZM PHINZAKO 2088987202075330924
[1330647649] AZ ZMOINK HPA 930234777158683487
[1680769145] IOAMK NPAZHZ  1936360260516443048
**
