### ISSUE TITLE
[BUG] Can't navigate to local host

### ISSUE THREAD

**Issue by CainScott** [0xSteeW/JokerCord#60]
im unable to navigate to the local host link to change my preferences to add my token.

**Comment by joker-ware** [comment]
Hello. I will push a new version today with bug fixes. Please be patient.

**Comment by CainScott** [comment]
Does this mean the issue will be resolved later? Thank You

**Comment by joker-ware** [comment]
Quite possibly.

**Comment by joker-ware** [comment]
New update has been released. Let me know if it works

**Comment by CainScott** [comment]
i've used this a while back and it worked following guide, now however i cant follow the local host link on the guide i believe im doing everything correctly

**Comment by CainScott** [comment]
i read another issue about this, joker.py closes itself once opened

**Comment by CainScott** [comment]
(Windows)

**Comment by getbah** [comment]
ye, i have the same issue, its autoclose

**Comment by getbah** [comment]
lol, problem was in bot_thread.py
Last sentence , if wrote print e, instead of print(e).
This cause autoclose

**Comment by joker-ware** [comment]
Sorry I fixed the error. Thanks for noticing. https://discord.gg/S54EKpt

**Comment by joker-ware** [comment]
@CainScott please contact me on Discord

**Comment by NightcoreRYT** [comment]
I'm having the same issue. I can't navigate to http://localhost:5555/home on the same device. Error: Refused to connect

**Comment by NightcoreRYT** [comment]
![download](https://user-images.githubusercontent.com/31454793/74836733-e3d59500-5317-11ea-80bb-f66a779d8396.png)

Heres an example of what it looks like

**Comment by Motzumoto** [comment]
> I'm having the same issue. I can't navigate to http://localhost:5555/home on the same device. Error: Refused to connect
> 
> EDIT: Found a solution for those wanting to view the website on a different device like phones etc. Download ngrok for your pc and set it up. Then follow the guide.
> For a quick startup when you've got it all set up, type: ngrok http 5555
> 
> This will use the following port aka 5555 and create a website you can use to view it from anywhere. As you can see in the image below, I'm on my mobile data and it still works
> 
> ![Screenshot_20200219-011416_Chrome](https://user-images.githubusercontent.com/31454793/74792385-35990380-52b5-11ea-88f3-36c0bd2719ea.jpg)

Mmm,I'm running the bot on my phone and have no errors. When it randomly stops just click start spamming again and it continues. Running this on Android is honestly better than on my computer
