### ISSUE TITLE
Never Catch Nidoran Pokemon. [BUG]

### ISSUE THREAD

**Issue by arghiz** [0xSteeW/JokerCord#61]
**Describe the bug**
I just realised the bot never catched this pokemon.

To be exact, I'm talking about this dude:
[https://cdn.discordapp.com/attachments/675684488617000981/677227703333683253/PokecordSpawn.jpg](https://cdn.discordapp.com/attachments/675684488617000981/677227703333683253/PokecordSpawn.jpg)

**To Reproduce**
I thought the spawn for the next pokemon was too early, but it's not.
Can you check again? Is it because of the male and female symbol?

**Operating system**
MacOS.

**Comment by joker-ware** [comment]
I thought I had fixed that some versions ago. I'll see what I can do.

**Comment by arghiz** [comment]
I realized it catches the male, but not the female one. So I catch 0 Nidoran female so far. Thank you.
If you already know the solution please let me know the step.

**Comment by joker-ware** [comment]
I will change this today.
