### ISSUE TITLE
Spam Isn’t Working

### ISSUE THREAD

**Issue by BluestGarbage** [0xSteeW/JokerCord#64]
I currently have the spam set up for 5 channels and it won’t spam in a single one, I saved the changes and made sure they had their names highlighted in blue and rebooted multiple times but there is still no spamming happening

**Comment by joker-ware** [comment]
Sorry, you have to click "Start spamming" in settings.

**Comment by BluestGarbage** [comment]
my settings tab only has "Check for updates", "Customize lists". "Enable/Disable guilds", and "Activate spam", with "Refresh Channels" At the bottom, and in the activate spam tab, there's no option to start spamming. Sorry to bother. 
![Capture](https://user-images.githubusercontent.com/60998294/74583060-5b09d280-4f80-11ea-8699-39666f9282bc.PNG)

**Comment by Bilibox** [comment]
@BluestGarbage You have to scroll down its below refresh channels
