### ISSUE TITLE
website

### ISSUE THREAD

**Issue by ShreyashKira** [0xSteeW/JokerCord#67]
I m not able to open the website

**Comment by joker-ware** [comment]
Please provide more information.

**Comment by K11AnimeZone** [comment]
idk saying nerwork issue. i m not able to open the website

**Comment by joker-ware** [comment]
Can you send a screenshot of the console?

**Comment by FerretShiny** [comment]
when you reboot the bot, you have to take the /home out of the localhost:5555 in the address bar

**Comment by K11AnimeZone** [comment]
whenever I open joker.py a tab opens and close automatically
