### ISSUE TITLE
Need help setting up channels

### ISSUE THREAD

**Issue by ryanMD3084** [0xSteeW/JokerCord#68]
Hi , first of , great bot little spammer/catcher you made ^^ , why im making post right now is because i cant seem to get it to spam on certain channels because i cant find where to set that up on the jokercord website , when i go to edit preference ,it only asks for my token , which i already gave. I used the previous versions and remember being able to setup the channel i want it spamming in ,in the preference settings , did it change? where  do i set it up now?.

**Comment by joker-ware** [comment]
Yep! It did change. Now you can multi spam by going to the webpage>settings>enable/disable channels>click on the ones you want (they should turn blue), then reboot, go to settings again and click start spamming.

**Comment by ryanMD3084** [comment]
Ah i see , thanks for the fast reply , can you also tell me how do i change the message it spams?

**Comment by Bilibox** [comment]
@ryanMD3084 theres no way in the settings. 
If you edit Bot_thread.py Search for the line 
await channelInstance.send(str(random.randint(0,9999999)))
and change 
(random.randint(0,9999999)
with 
"What you want it to output"
Be sure to keep the quotation marks
