### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by Technolord3233** [0xSteeW/JokerCord#69]
The moment i launch Joker.py it opens then closes immediately. I installed python with path and everything, and followed the guide

**Comment by FerretShiny** [comment]
did you launch it from the directory its installed in?

**Comment by Technolord3233** [comment]
i didnt move it anywhere if thats what you mean

**Comment by FerretShiny** [comment]
._.

can you send a screenshot?
or a gif?

**Comment by Technolord3233** [comment]
of what? When I open joker.py I see a flash on my screen, of the black box opening, then it immediatly disappears

**Comment by FerretShiny** [comment]
hmmm

**Comment by Technolord3233** [comment]
![image](https://user-images.githubusercontent.com/40223320/74598617-9adbd180-50c8-11ea-874a-2d9f84cb1097.png)

**Comment by Technolord3233** [comment]
thats te folder if it makes a difference

**Comment by FerretShiny** [comment]
ye
did you run the pip3 install discord.py requests flask command?

**Comment by Technolord3233** [comment]
Yes, also made sure to enable PATH thing
I also uninstalled and reinstalled both Python and the discord.py requests flask stuff

**Comment by FerretShiny** [comment]
what version of python is it?

**Comment by Technolord3233** [comment]
Latest version on the website

**Comment by FerretShiny** [comment]
welp 
i cant help you idk

**Comment by Technolord3233** [comment]
Ty for trying

**Comment by FerretShiny** [comment]
talk to jokerware on discord

**Comment by Technolord3233** [comment]
how? i cant find his discord name

**Comment by joker-ware** [comment]
https://discord.gg/S54EKpt
