### ISSUE TITLE
[FEATURE] Multiple Tokens maybe? 

### ISSUE THREAD

**Issue by Motzumoto** [0xSteeW/JokerCord#70]
My friend wants me to use the bot on his account, and i added his token along with mine and it semi worked, it didnt spam for him but it did try to catch pokemon, So it kinda works but i dont think it has the complete functionality yet. I hope this gets added in the future

**Comment by FerretShiny** [comment]
that would be nice! or, sometime down the road, Joker could make the bot be able to make its own dummy accounts and use those instead of ours... we are no where near that tho

**Comment by NightcoreRYT** [comment]
Or just run two instances of the bot with different tokens?

**Comment by Motzumoto** [comment]
> Or just run two instances of the bot with different tokens?
> Make a copy of the bot folder and change the token in one.
Tried that. It refreshes and makes the tokens the same
