### ISSUE TITLE
Selected spam channels doesn't get activated

### ISSUE THREAD

**Issue by Hakuteiken3** [0xSteeW/JokerCord#71]
Selected spam channels doesn't get activated. It's the hardest bot to use.

**Comment by Motzumoto** [comment]
It does just give it time, select the spam channels by clicking the drop down menu thing and then click on them.

**Comment by joker-ware** [comment]
I do know it isn't the simplest bot, but that's caused by the demonic Asyncio coroutines and jsons not updating after you change them so you have to reboot. I would totally rewrite this but I don't have the time. Sorry for the inconveniences.

**Comment by FerretShiny** [comment]
also when you select the spam channels, reboot the bot, go back to settings, scroll down, and hit start spamming. spamming doesnt automatically start when you select the channels.

**Comment by Hakuteiken3** [comment]
> also when you select the spam channels, reboot the bot, go back to settings, scroll down, and hit start spamming. spamming doesnt automatically start when you select the channels.

How? There are lots of channels and no one of them turns into blue color. It doesn't matter if I wait for hours.

**Comment by joker-ware** [comment]
You have to click them in the dropdown at the top
