### ISSUE TITLE
Dunno what dis is

### ISSUE THREAD

**Issue by ghost** [0xSteeW/JokerCord#73]
It shows cusers appdata python lib site-packages discord abc.py or http.py line missing

**Comment by joker-ware** [comment]
Can you send a screenshot. It's very hard to debug with that little info

**Comment by GunnerGolu** [comment]
![Screenshot (733)](https://user-images.githubusercontent.com/54153793/74760081-e2688600-529f-11ea-9180-62cf716fc3bc.png)

**Comment by GunnerGolu** [comment]
I mean it catches for few minutes but after that this pops up.

**Comment by joker-ware** [comment]
Seems like a connection problem. Or Discord's api problem.

**Comment by FerretShiny** [comment]
i get that whenever i leave it open and my pc falls asleep... so yea its probably connection

**Comment by GunnerGolu** [comment]
ok

**Comment by GunnerGolu** [comment]
so i have to start spam in webpage every time?

**Comment by joker-ware** [comment]
Yes, unfortunately.

**Comment by GunnerGolu** [comment]
i saw u removed ur discord server link, why?

**Comment by joker-ware** [comment]
I didn't, just moved it to the top of the Readme

**Comment by NightcoreRYT** [comment]
@GunnerGolu there's a way around it I think. Are you using a laptop or desktop?

**Comment by GunnerGolu** [comment]
im on laptop

**Comment by GunnerGolu** [comment]
![Screenshot (735)](https://user-images.githubusercontent.com/54153793/74824991-26569c00-532f-11ea-9d6c-1580bef0979d.png)
Also whats this?
