### ISSUE TITLE
New Md5

### ISSUE THREAD

**Issue by erin804** [0xSteeW/JokerCord#77]
It seems all the pokemons have new md5's so the whole pokemon hashes needs to be updated.

**Comment by joker-ware** [comment]
Thanks for telling me. When I get home I will test it out a bit and update the hashes if necessary.

**Comment by joker-ware** [comment]
Hello, we have some troubles. I recommend you to join the discord to be updated. Pleas join with an alt to prevent unwanted bans. https://discord.gg/S54EKpt
