### ISSUE TITLE
My JokerCord spam but do not caught any pokemon

### ISSUE THREAD

**Issue by dasen14** [0xSteeW/JokerCord#79]
I saw you have another issues with this problem but my real problem is in webpage, because i put my token in website and i rebooted but it doesnt make any changes so i cant go to webpage>settings>enable/disable guilds because i doesnt appears. Pls can you help me, the bot spams numbers but doesnt catch any pokemon
![image](https://user-images.githubusercontent.com/62202621/76699298-8c271100-66ac-11ea-85f1-b313470fc7b4.png)

**Comment by joker-ware** [comment]
Use the other bot. https://github.com/joker-ware/nearix-beta/releases/tag/v2.3.0-beta

**Comment by dasen14** [comment]
ty <3

**Comment by dasen14** [comment]
What i have to write here? 
![image](https://user-images.githubusercontent.com/62202621/76700075-eaa3bd80-66b3-11ea-861a-ef05047fbf19.png)

**Comment by joker-ware** [comment]
You visited wrong page, go to http://localhost:9898/settings

**Comment by dasen14** [comment]
okey, so now in this?
![image](https://user-images.githubusercontent.com/62202621/76700105-3ce4de80-66b4-11ea-9ee3-e06909c08622.png)

**Comment by joker-ware** [comment]
Do all your servers show there?

**Comment by dasen14** [comment]
yes

**Comment by joker-ware** [comment]
In the text fields the first one is for catch delay and the second is for prefix. After typing bot click submit.

**Comment by dasen14** [comment]
i dont understand what to type in prefix. Are you spanish Daniel?

**Comment by joker-ware** [comment]
Yes

**Comment by dasen14** [comment]
mira el comentario de arriba

**Comment by joker-ware** [comment]
Únete al Discord si necesitas: https://discord.gg/UHVY23g

**Comment by dasen14** [comment]
me están verificando
