### ISSUE TITLE
What to do to not get a ban?

### ISSUE THREAD

**Issue by XdfgsaX** [0xSteeW/JokerCord#80]
Tell me, what settings do you need to not get a ban? Yesterday I was banned from 1 account for 8 + hours of Catch on 3 channels, today I used a different account - I got a ban in 15 minutes. . .
settings -
spam - 4
catch - 8
What am I doing wrong ? And how do you use it?

**Comment by Bilibox** [comment]
Does a normal human sit at a computer for 8+ hours a day constantly watching 3 different discord channels trying to catch pokemon and spamming?
Would a normal human at some point get us to eat or use the restroom or take a break?

The problem is you're running it like a bot and not a human
