### ISSUE TITLE
I don't have access to all preferences !

### ISSUE THREAD

**Issue by JulotCraft** [0xSteeW/JokerCord#90]
Hey ! I have a problem, I can't access to spam interval, spam text and other...

![image](https://user-images.githubusercontent.com/52045649/79625093-d32e7900-8126-11ea-8bca-31d649e9410d.png)

I have only the "Input your token"

Thanks

**Comment by 0xSteeW** [comment]
Those options were removed in favor of the options menu. Anyways bot is unsupported.
